version: "3"
services:
 appwrite-webhook-proxy:
  build: .
  ports:
   - 4444:4444
  volumes:
   - ./:/usr/src/myapp
  environment:
   - WEBHOOK_PROXY_APPWRITE_FUNCTION_ID
   - WEBHOOK_PROXY_APPWRITE_API_KEY
   - WEBHOOK_PROXY_APPWRITE_PROJECT_ID
   - WEBHOOK_PROXY_APPWRITE_ENDPOINT
